#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'assets/release_metadata';O.mkdir(parents=True,exist_ok=True)
def sha(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
def entry(result_id,experiment,status,dataset,model,params,n,effect,ci,relative,source,boundary,**extra):
 return {'result_id':result_id,'experiment':experiment,'status':status,'dataset':dataset,'model':model,'parameter_count':params,'sample_or_family_count':n,'effect':effect,'ci95':ci,'relative_effect':relative,'source_audit_path':source,'source_artifact_sha256':sha(source),'interpretation_boundary':boundary,**extra}
results=[
 entry('lmd_census_80_10_10','Full-LMD leakage census','FULL_LMD_CENSUS_PARTIAL','LMD','not_applicable',None,{'identities':178561,'families':140427,'multi_member_families':20797,'multi_member_files':58931},{'80_10_10_test_family_contamination':.2765669342,'80_10_10_test_file_contamination':.297670108,'90_5_5_test_family_contamination':.3030,'90_10_test_family_contamination':.2934},None,None,'audits/full_lmd_leakage_census_20260809/monte_carlo_results.json','Full corpus supports file, byte-dedup, and family-aware protocols; canonical and track-order cache covers only 4,300 files.'),
 entry('lmd_transformer_l','Controlled family leakage confirmatory','CONFIRMATORY_FAMILY_LEAKAGE_PASS','LMD','Transformer-L',17821056,100,-.11531665896,[-.13244426636,-.09896393327],.13617306555,'audits/confirmatory_family_leakage_execution_20260804/primary_estimand.json','Treated-family, control-adjusted effect; not a universal dataset property.',negative_families='99/100',seeds_negative='3/3'),
 entry('lmd_structurally_nonexact','Structurally non-exact secondary stratum','SUPPORTED_SECONDARY','LMD','Transformer-L',17821056,95,-.113316,[-.13075997022,-.09706527336],None,'audits/family_aware_mitigation_final_20260808/controlled_mitigation_effect.json','Frozen paper-facing structurally-nonexact analysis under the adopted canonicalization.'),
 entry('lmd_difficult_stratum','Difficulty secondary stratum','SUPPORTED_SECONDARY','LMD','Transformer-L',17821056,None,-.09295846361,None,None,'audits/confirmatory_paper_readiness_20260806/difficulty_strata.json','Secondary descriptive difficulty stratum.'),
 entry('transformer_s','Capacity study','CAPACITY_AND_ARCHITECTURE','LMD','Transformer-S',10942512,100,-.07759306071,[-.08953893738,-.06633320981],.08571583116,'audits/transformer_scale_execution_20260810/scale_effects.json','Capacity and architecture association, not a universal scaling law.'),
 entry('transformer_m','Capacity study','CAPACITY_AND_ARCHITECTURE','LMD','Transformer-M',13658064,100,-.08571254853,[-.09882363737,-.07292632320],.10397596524,'audits/transformer_scale_execution_20260810/scale_effects.json','Capacity and architecture association, not a universal scaling law.'),
 entry('tcn_384','Second architecture TCN','SECOND_ARCHITECTURE_TCN_REPLICATION_REJECTED','LMD','TCN-384',10753536,100,-.03172214738,[-.03777569707,-.02634451010],.02530064531,'audits/second_architecture_tcn_execution_20260807/primary_estimand.json','Smaller statistically consistent same-direction effect; preregistered practical replication threshold failed.',formal_replication=False,directionally_consistent=True,negative_families='99/100',seeds_negative='3/3'),
 entry('mitigation_4300','Mitigation comparison','FAMILY_AWARE_MITIGATION_SUPPORTED','LMD cached pool','not_applicable',None,4300,{'S0_cross_split':177,'S1_cross_split':161,'family_aware_cross_split':0,'family_aware_reassigned':.2595348837,'delete_multi_token_loss':.2283570490},None,None,'audits/family_aware_mitigation_final_20260808/split_comparison.json','4,300-file frozen pool; zero known overlap under adopted family definition.'),
 entry('pdmx_feasibility_v2','PDMX metadata feasibility','PDMX_EXTERNAL_FEASIBILITY_V2_PASS','PDMX Tier-A','not_applicable',None,322,None,None,None,'audits/pdmx_external_feasibility_v2_20260812/candidate_family_summary.json','Metadata feasibility only; not a MIDI structure or model-effect PASS.'),
 entry('pdmx_structure_gate','PDMX original 100-family structure gate','PDMX_MIDI_STRUCTURE_FAIL','PDMX Tier-A','not_applicable',None,{'tier_a':322,'midi_eligible':79,'structurally_nonexact':67},None,None,None,'audits/pdmx_midi_structure_20260812/family_eligibility.json','Frozen tokenizer eligibility left 67 structurally-nonexact families, below the original 100-family requirement.'),
 entry('pdmx_reduced','Reduced-cohort external estimation','PDMX_REDUCED_EXTERNAL_EFFECT_SUPPORTED','PDMX reduced Tier-A','Transformer-L',17821056,67,-.06777620934,[-.08321508803,-.05317508547],.11068005018,'audits/pdmx_reduced_external_execution_20260812/primary_effect.json','Only Tier-A catalog-anchored, structurally-nonexact, 4/4, 1024-context-eligible reduced cohort.',original_100_family_gate='failed',reduced_cohort_supported=True,treated_n=67,seeds=[-.07203421761,-.06272127534,-.06857313509],negative_family_rate=.9552238806,control_drift=-.00169370216,clean_validation_drift=-.002673)
]
(O/'result_registry.json').write_text(json.dumps({'release':'LeakageBench-MIDI v1.0.0-rc1','results':results},indent=2,sort_keys=True)+'\n')
claims=[
 ('C1','Random file splitting creates substantial known same-family train/test overlap in LMD.','supported','audits/full_lmd_leakage_census_20260809/monte_carlo_results.json','Random file splitting creates substantial known same-family overlap in LMD.','All LMD leakage is known or measured.'),
 ('C2','Controlled family leakage inflates Transformer evaluation on treated families.','supported','audits/confirmatory_family_leakage_execution_20260804/primary_estimand.json','Controlled designated-donor exposure reduced treated-family NLL relative to controls.','Leakage always improves every model or dataset.'),
 ('C3','The Transformer effect persists for structurally non-exact variants.','supported_secondary','audits/family_aware_mitigation_final_20260808/controlled_mitigation_effect.json','The frozen structurally-nonexact LMD stratum showed a same-direction effect.','All non-exact works are distinct compositions.'),
 ('C4','Leakage susceptibility varies with architecture and Transformer capacity.','supported','audits/transformer_scale_execution_20260810/scale_effects.json','Results support capacity-and-architecture dependence in the evaluated configurations.','Universal scaling law; replicated across architectures.'),
 ('C5','A reduced PDMX external cohort supports a same-direction family-specific effect.','supported_limited','audits/pdmx_reduced_external_execution_20260812/primary_effect.json','A 67-family eligible reduced PDMX cohort supports a same-direction effect.','Full-PDMX replication; original 100-family gate passed.'),
 ('C6','Exact deduplication alone does not remove known arrangement-family leakage.','supported','audits/family_aware_mitigation_final_20260808/split_comparison.json','Exact deduplication left 161 known cross-split families in the frozen 4,300-file pool.','Exact deduplication is ineffective for every corpus.'),
 ('C7','Family-aware component splitting removes known family overlap without deleting data.','supported','audits/family_aware_mitigation_final_20260808/family_aware_data_cost.json','Family-aware assignment achieved zero known family overlap with 100% retention in the frozen pool.','Guaranteed zero latent leakage without complete family labels.')]
items=[{'claim_id':i,'claim_text':t,'support_status':s,'supporting_artifact':p,'supporting_artifact_sha256':sha(p),'permitted_wording':ok,'forbidden_wording':bad} for i,t,s,p,ok,bad in claims]
(O/'claim_registry.json').write_text(json.dumps({'release':'LeakageBench-MIDI v1.0.0-rc1','claims':items},indent=2,sort_keys=True)+'\n')
